apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: devops-test-acr-registry.ap-southeast-1.cr.aliyuncs.com/jgy-test/jgy-test:b8cbd93440663a9b30e32a455c247e2243456afa
        ports:
        - containerPort: 80
